# Generated by Django 4.1 on 2022-09-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicedetails",
            name="status",
            field=models.CharField(
                choices=[("Online", "Online"), ("Offline", "Offline")],
                default="Offline",
                max_length=7,
            ),
        ),
    ]
