# Generated by Django 4.1 on 2022-09-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0002_devicedetails_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicedetails",
            name="master_status",
            field=models.CharField(
                choices=[("YES", "Yes"), ("NO", "No")], default="NO", max_length=3
            ),
        ),
    ]
