# Generated by Django 4.1 on 2022-09-20 11:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="userDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(blank=True, max_length=25)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("None", "None"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("User", "User"),
                            ("Visitor", "Visitor"),
                            ("Blocklist", "Blocklist"),
                        ],
                        max_length=10,
                    ),
                ),
                ("floor_number", models.IntegerField(blank=True, null=True)),
                ("room_number", models.IntegerField(blank=True, null=True)),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "end_time",
                    models.DateTimeField(
                        default=datetime.datetime(2037, 12, 31, 23, 59, 59)
                    ),
                ),
                (
                    "IP",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="device.devicedetails",
                    ),
                ),
            ],
        ),
    ]
