# Generated by Django 4.1 on 2022-09-21 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0002_devicedetails_status"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="IP",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="device.devicedetails"
            ),
        ),
    ]
