# Generated by Django 4.1 on 2022-09-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_userdetails_image_alter_userdetails_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="image",
            field=models.FileField(null=True, upload_to="Face/%Y/%m/%d/"),
        ),
    ]
