# Generated by Django 4.1 on 2022-09-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_userdetails_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="Face/%Y/%m/%d/"),
        ),
    ]
