# Generated by Django 4.1 on 2022-10-03 07:26

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_userdetails_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=user.models.upload_to
            ),
        ),
    ]
