# Generated by Django 4.1 on 2022-09-19 10:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="deviceDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField(null=True, unique=True)),
                ("port", models.IntegerField(default=80)),
                ("user_id", models.CharField(max_length=10)),
                ("password", models.CharField(max_length=10)),
                (
                    "master_status",
                    models.CharField(choices=[("YES", "Y"), ("NO", "N")], max_length=3),
                ),
            ],
        ),
        migrations.CreateModel(
            name="userDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(blank=True, max_length=25)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("None", "None"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("User", "User"),
                            ("Visitor", "Visitor"),
                            ("Blocklist", "Blocklist"),
                        ],
                        max_length=10,
                    ),
                ),
                ("floor_number", models.IntegerField(blank=True, null=True)),
                ("room_number", models.IntegerField(blank=True, null=True)),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(default="2037-12-31T 23:59:59")),
                (
                    "IP",
                    models.ForeignKey(
                        default="0.0.0.0",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.devicedetails",
                    ),
                ),
            ],
        ),
    ]
