# Generated by Django 4.1 on 2022-09-19 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_userdetails_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="IP",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.devicedetails",
            ),
        ),
    ]
