# Generated by Django 4.1 on 2022-09-19 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_userdetails_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.datetime(2037, 12, 31, 23, 59, 59)
            ),
        ),
    ]
