# Generated by Django 4.1 on 2022-09-20 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_userdetails_end_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdetails",
            name="IP",
        ),
        migrations.DeleteModel(
            name="deviceDetails",
        ),
        migrations.DeleteModel(
            name="userDetails",
        ),
    ]
